### ISSUE TITLE
Attempts to open videos, channels, or check subs gives 500 Uncaught Exception

### ISSUE THREAD

**Issue by SlidingHorn** [user234683/youtube-local#103]
**Edit:** *Now it's working again....not sure what the deal is....Going to leave this open for now, and if I don't have any further issues by this time tomorrow, I'll close it*

---

```
Traceback (most recent call last):
  File "/home/user/downloads/youtube-local-2.7.0/youtube/util.py", line 270, in fetch_url_response
    response = pool.request(method, url, headers=headers, body=data,
  File "/usr/lib/python3.9/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/usr/lib/python3.9/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/poolmanager.py", line 417, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/usr/lib/python3.9/site-packages/urllib3/poolmanager.py", line 417, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/usr/lib/python3.9/site-packages/urllib3/poolmanager.py", line 417, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/usr/lib/python3.9/site-packages/urllib3/poolmanager.py", line 404, in urlopen
    retries = retries.increment(method, url, response=response, _pool=conn)
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='m.youtube.com', port=443): Max retries exceeded with url: https://m.youtube.com/playlist?list=UUxSQZf38voCR7s4EMsc4TDw&pbj=1 (Caused by ResponseError('too many redirects'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/user/downloads/youtube-local-2.7.0/youtube/channel.py", line 315, in get_channel_page
    return get_channel_page_general_url('https://www.youtube.com/channel/' + channel_id, tab, request, channel_id)
  File "/home/user/downloads/youtube-local-2.7.0/youtube/channel.py", line 271, in get_channel_page_general_url
    util.check_gevent_exceptions(*tasks)
  File "/home/user/downloads/youtube-local-2.7.0/youtube/util.py", line 590, in check_gevent_exceptions
    raise task.exception
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/user/.local/lib/python3.9/site-packages/cachetools/func.py", line 66, in wrapper
    v = func(*args, **kwargs)
  File "/home/user/downloads/youtube-local-2.7.0/youtube/channel.py", line 156, in get_number_of_videos_channel
    response = util.fetch_url(url, headers_mobile,
  File "/home/user/downloads/youtube-local-2.7.0/youtube/util.py", line 300, in fetch_url
    response, cleanup_func = fetch_url_response(
  File "/home/user/downloads/youtube-local-2.7.0/youtube/util.py", line 274, in fetch_url_response
    exception_cause = e.__context__.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
```

I was apparently running 2.7.0 not knowing there was an update, but after upgrading to 2.7.1, the issue persists.
